services:
  - type: web
    name: licenciamento-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 api_server.py"
    envVars:
      - key: PORT
        value: "5000"  # Definindo a porta padrão
